In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import sqlite3 as sql
from dotenv import load_dotenv, dotenv_values
import os

load_dotenv(Path.cwd().parent / ".env")

True

In [13]:
data = pd.read_csv(f'{Path.cwd().parent / "companies_house_data.csv"}')

C:\Users\Ink\AppData\Local\Temp\ipykernel_42764\2840432469.py:1: DtypeWarning: Columns (0: RegAddress.POBox, 1: PreviousName_5.CONDATE, 2:  PreviousName_5.CompanyName, 3: PreviousName_6.CONDATE, 4:  PreviousName_6.CompanyName, 5: PreviousName_7.CONDATE, 6:  PreviousName_7.CompanyName, 7: PreviousName_8.CONDATE, 8:  PreviousName_8.CompanyName, 9: PreviousName_9.CONDATE, 10:  PreviousName_9.CompanyName, 11: PreviousName_10.CONDATE, 12:  PreviousName_10.CompanyName) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(f'{Path.cwd().parent / "companies_house_data.csv"}')

In [14]:
active_boys = data.loc[data["CompanyStatus"] == "Active"]
active_boys = active_boys.loc[active_boys["Accounts.AccountCategory"] != "DORMANT"]
active_boys = active_boys.loc[active_boys["CompanyName"].str.contains("LTD|LIMITED|LLP|LIMITED LIABILITY PARTNERSHIP", case=False, na=False)]
active_boys.rename(columns={" CompanyNumber": "CompanyNumber", "IncorporationDate": "DateOfCreation","RegAddress.PostTown":"Town", "RegAddress.County":"County", "RegAddress.PostCode": "PostCode"}, inplace=True)

In [15]:
active_boys.iloc[500]

CompanyName                                                            0 QUARTERS LTD
CompanyNumber                                                                16710077
RegAddress.CareOf                                                                 NaN
RegAddress.POBox                                                                  NaN
RegAddress.AddressLine1                                                   2 EAST ROAD
 RegAddress.AddressLine2                                                          NaN
Town                                                                           LONDON
County                                                                            NaN
RegAddress.Country                                                            ENGLAND
PostCode                                                                      E15 3QR
CompanyCategory                                               Private Limited Company
CompanyStatus                                                                  Active
CountryOfOrigin                                                        United Kingdom
DissolutionDate                                                                   NaN
DateOfCreation                                                             11/09/2025
Accounts.AccountRefDay                                                           30.0
Accounts.AccountRefMonth                                                          9.0
Accounts.NextDueDate                                                       11/06/2027
Accounts.LastMadeUpDate                                                           NaN
Accounts.AccountCategory                                            NO ACCOUNTS FILED
Returns.NextDueDate                                                        09/10/2026
Returns.LastMadeUpDate                                                            NaN
Mortgages.NumMortCharges                                                            0
Mortgages.NumMortOutstanding                                                        0
Mortgages.NumMortPartSatisfied                                                      0
Mortgages.NumMortSatisfied                                                          0
SICCode.SicText_1                                             99999 - Dormant Company
SICCode.SicText_2                                                                 NaN
SICCode.SicText_3                                                                 NaN
SICCode.SicText_4                                                                 NaN
LimitedPartnerships.NumGenPartners                                                  0
LimitedPartnerships.NumLimPartners                                                  0
URI                                   http://business.data.gov.uk/id/company/16710077
PreviousName_1.CONDATE                                                            NaN
 PreviousName_1.CompanyName                                                       NaN
 PreviousName_2.CONDATE                                                           NaN
 PreviousName_2.CompanyName                                                       NaN
PreviousName_3.CONDATE                                                            NaN
 PreviousName_3.CompanyName                                                       NaN
PreviousName_4.CONDATE                                                            NaN
 PreviousName_4.CompanyName                                                       NaN
PreviousName_5.CONDATE                                                            NaN
 PreviousName_5.CompanyName                                                       NaN
PreviousName_6.CONDATE                                                            NaN
 PreviousName_6.CompanyName                                                       NaN
PreviousName_7.CONDATE                                                            NaN
 PreviousName_7.CompanyName                                                       NaN
PreviousName_8.CONDATE                                                            NaN
 PreviousName_8.CompanyName                                                       NaN
PreviousName_9.CONDATE                                                            NaN
 PreviousName_9.CompanyName                                                       NaN
PreviousName_10.CONDATE                                                           NaN
 PreviousName_10.CompanyName                                                      NaN
ConfStmtNextDueDate                                                        24/09/2026
 ConfStmtLastMadeUpDate                                                           NaN
Name: 744, dtype: object

In [16]:
active_boys["CompanyNumber"]

1          16092999
3          16873705
4          15073164
5          13522064
6          11006939
             ...
5698264    14418099
5698267    14079291
5698268    11044986
5698271    09511422
5698272    11457383
Name: CompanyNumber, Length: 4390812, dtype: str

In [17]:
active_boys.iloc[100]

CompanyName                                                           $10 CHIMP LIMITED
CompanyNumber                                                                  09646807
RegAddress.CareOf                                                                   NaN
RegAddress.POBox                                                                    NaN
RegAddress.AddressLine1                                              63 GRANTHAM AVENUE
 RegAddress.AddressLine2                                                  GREAT CORNARD
Town                                                                            SUDBURY
County                                                                              NaN
RegAddress.Country                                                              ENGLAND
PostCode                                                                       CO10 0ZG
CompanyCategory                                                 Private Limited Company
CompanyStatus                                                                    Active
CountryOfOrigin                                                          United Kingdom
DissolutionDate                                                                     NaN
DateOfCreation                                                               18/06/2015
Accounts.AccountRefDay                                                             30.0
Accounts.AccountRefMonth                                                            6.0
Accounts.NextDueDate                                                         31/03/2027
Accounts.LastMadeUpDate                                                      30/06/2025
Accounts.AccountCategory                                                   MICRO ENTITY
Returns.NextDueDate                                                          16/07/2017
Returns.LastMadeUpDate                                                       18/06/2016
Mortgages.NumMortCharges                                                              0
Mortgages.NumMortOutstanding                                                          0
Mortgages.NumMortPartSatisfied                                                        0
Mortgages.NumMortSatisfied                                                            0
SICCode.SicText_1                     70210 - Public relations and communications ac...
SICCode.SicText_2                                                                   NaN
SICCode.SicText_3                                                                   NaN
SICCode.SicText_4                                                                   NaN
LimitedPartnerships.NumGenPartners                                                    0
LimitedPartnerships.NumLimPartners                                                    0
URI                                     http://business.data.gov.uk/id/company/09646807
PreviousName_1.CONDATE                                                              NaN
 PreviousName_1.CompanyName                                                         NaN
 PreviousName_2.CONDATE                                                             NaN
 PreviousName_2.CompanyName                                                         NaN
PreviousName_3.CONDATE                                                              NaN
 PreviousName_3.CompanyName                                                         NaN
PreviousName_4.CONDATE                                                              NaN
 PreviousName_4.CompanyName                                                         NaN
PreviousName_5.CONDATE                                                              NaN
 PreviousName_5.CompanyName                                                         NaN
PreviousName_6.CONDATE                                                              NaN
 PreviousName_6.CompanyName                                                         NaN
PreviousName_7.CONDATE                                                              NaN
 PreviousName_7.CompanyName                                                         NaN
PreviousName_8.CONDATE                                                              NaN
 PreviousName_8.CompanyName                                                         NaN
PreviousName_9.CONDATE                                                              NaN
 PreviousName_9.CompanyName                                                         NaN
PreviousName_10.CONDATE                                                             NaN
 PreviousName_10.CompanyName                                                        NaN
ConfStmtNextDueDate                                                          22/12/2026
 ConfStmtLastMadeUpDate                                                      08/12/2025
Name: 188, dtype: object

In [18]:
active_names = active_boys[["CompanyName", "CompanyNumber","DateOfCreation","CompanyCategory", "Town","County","PostCode","SICCode.SicText_1","SICCode.SicText_2","SICCode.SicText_3","SICCode.SicText_4"]]

In [12]:
active_names

,CompanyName,CompanyNumber,DateOfCreation,CompanyCategory,Town,County,PostCode,SICCode.SicText_1,SICCode.SicText_2,SICCode.SicText_3,SICCode.SicText_4
0,! LTD,08209948,11/09/2012,Private Limited Company,HARROGATE,NaN,HG1 1ND,99999 - Dormant Company,NaN,NaN,NaN
1,!ABRIDGE TAX LTD,16092999,21/11/2024,Private Limited Company,HATFIELD,NaN,AL9 5BL,62020 - Information technology consultancy act...,NaN,NaN,NaN
2,!BIG IMPACT GRAPHICS LIMITED,11743365,28/12/2018,Private Limited Company,LONDON,NaN,EC1V 2NX,59112 - Video production activities,63120 - Web portals,74100 - specialised design activities,74201 - Portrait photographic activities
3,!FE NETWORK LIMITED,16873705,25/11/2025,Private Limited Company,"HARLOW, ESSEX",NaN,CM20 1YS,86210 - General medical practice activities,NaN,NaN,NaN
4,!NFLECTION ADVISORY LIMITED,15073164,15/08/2023,Private Limited Company,POTTERS BAR,HERTFORDSHIRE,EN6 2DA,70229 - Management consultancy activities othe...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5698269,“NEIGH”OMI’S EQUINE TRANSPORT AND HIRE LTD,11224854,26/02/2018,Private Limited Company,ESSEX,NaN,IG1 3AD,52290 - Other transportation support activities,NaN,NaN,NaN
5698270,“Q-STAR TELENERGY HOLDINGS LIMITED,SC655320,21/02/2020,Private Limited Company,RENFREWSHIRE,NaN,PA4 8SG,61200 - Wireless telecommunications activities,61300 - Satellite telecommunications activities,61900 - Other telecommunications activities,62090 - Other information technology service a...
5698271,“SAIL IN GREECE ADVENTURES” LTD,09511422,26/03/2015,Private Limited Company,LONDON,LONDON,EC3V 3NG,79120 - Tour operator activities,NaN,NaN,NaN
5698272,“THE GREENHOUSE” COMPANY LTD,11457383,10/07/2018,Private Limited Company,SHREWSBURY,SHROPSHIRE,SY1 1XF,56101 - Licensed restaurants,NaN,NaN,NaN
5698273,€ RECYCLING LIMITED,04528854,06/09/2002,Private Limited Company,BEDFORD,NaN,MK42 0PQ,99999 - Dormant Company,NaN,NaN,NaN

In [19]:
active_names["CompanyName"] = active_names["CompanyName"].str.lstrip("!")

In [20]:
active_names

,CompanyName,CompanyNumber,DateOfCreation,CompanyCategory,Town,County,PostCode,SICCode.SicText_1,SICCode.SicText_2,SICCode.SicText_3,SICCode.SicText_4
1,ABRIDGE TAX LTD,16092999,21/11/2024,Private Limited Company,HATFIELD,NaN,AL9 5BL,62020 - Information technology consultancy act...,NaN,NaN,NaN
3,FE NETWORK LIMITED,16873705,25/11/2025,Private Limited Company,"HARLOW, ESSEX",NaN,CM20 1YS,86210 - General medical practice activities,NaN,NaN,NaN
4,NFLECTION ADVISORY LIMITED,15073164,15/08/2023,Private Limited Company,POTTERS BAR,HERTFORDSHIRE,EN6 2DA,70229 - Management consultancy activities othe...,NaN,NaN,NaN
5,NFOGENIE LTD,13522064,21/07/2021,Private Limited Company,LONDON,GREATER LONDON,WC2H 9JQ,58290 - Other software publishing,NaN,NaN,NaN
6,NNOV8 LIMITED,11006939,11/10/2017,Private Limited Company,EDENBRIDGE,NaN,TN8 5NF,62090 - Other information technology service a...,70229 - Management consultancy activities othe...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5698264,‘HEOL CHWARAE RÔL LTD,14418099,13/10/2022,"PRI/LTD BY GUAR/NSC (Private, limited by guara...",PONTYPRIDD,NaN,CF38 1TQ,93290 - Other amusement and recreation activit...,NaN,NaN,NaN
5698267,"“34 HALLAM ROAD FLAT MANAGEMENT COMPANY"" LIMITED",14079291,29/04/2022,Private Limited Company,CLEVEDON,NaN,BS21 7NE,99999 - Dormant Company,NaN,NaN,NaN
5698268,“ARTIS UK” LIMITED,11044986,02/11/2017,Private Limited Company,SURBITON,NaN,KT6 5LX,41202 - Construction of domestic buildings,NaN,NaN,NaN
5698271,“SAIL IN GREECE ADVENTURES” LTD,09511422,26/03/2015,Private Limited Company,LONDON,LONDON,EC3V 3NG,79120 - Tour operator activities,NaN,NaN,NaN
5698272,“THE GREENHOUSE” COMPANY LTD,11457383,10/07/2018,Private Limited Company,SHREWSBURY,SHROPSHIRE,SY1 1XF,56101 - Licensed restaurants,NaN,NaN,NaN

In [21]:
def add_company_names_to_db(df):
    con = sql.connect(Path.cwd().parent / os.getenv("DB_URL"))
    cur = con.cursor()

    for index, row in df.iterrows():
        cur.execute("INSERT INTO companies (name, company_id, date_of_creation, company_type, town, county, post_code) VALUES (?, ?, ?, ?, ?, ?, ?)", (row["CompanyName"], row["CompanyNumber"], row["DateOfCreation"], row["CompanyCategory"], row["Town"], row["County"], row["PostCode"]))
    con.commit()
    con.close()
    
def add_sic_codes_to_db(df):
    con = sql.connect(Path.cwd().parent / os.getenv("DB_URL"))
    cur = con.cursor()

    for index, row in df.iterrows():
        sic_codes = row[["SICCode.SicText_1", "SICCode.SicText_2", "SICCode.SicText_3", "SICCode.SicText_4"]].dropna().tolist()
        if 'None Supplied' in sic_codes:
            sic_codes.remove('None Supplied')
        for i in sic_codes:
            code, text = i.split(" - ")
            try:
                cur.execute("INSERT INTO sic_codes (sic_id, sector_name) VALUES (?, ?)", (code.strip(), text.strip()))
            except sql.IntegrityError:
                continue
    
    con.commit()
    con.close()        
    
def add_company_sic_codes_to_db(df):
    con = sql.connect(Path.cwd().parent / os.getenv("DB_URL"))
    cur = con.cursor()

    for index, row in df.iterrows():
        company_id = row["CompanyNumber"]
        sic_codes = row[["SICCode.SicText_1", "SICCode.SicText_2", "SICCode.SicText_3", "SICCode.SicText_4"]].dropna().tolist()
        if 'None Supplied' in sic_codes:
            sic_codes.remove('None Supplied')
        for i in sic_codes:
            code, text = i.split(" - ")
            try:
                cur.execute("INSERT INTO companies_sic_codes (company_id, sic_code) VALUES (?, ?)", (company_id, code.strip()))

            except sql.IntegrityError:
                continue

    con.commit()
    con.close()

In [22]:
add_company_names_to_db(active_names)

In [52]:
add_sic_codes_to_db(active_names)

In [23]:
add_company_sic_codes_to_db(active_names)

In [22]:
sic_codes = data.iloc[-1][["SICCode.SicText_1", "SICCode.SicText_2", "SICCode.SicText_3", "SICCode.SicText_4"]].dropna().tolist()

In [24]:
sic_codes.remove('None Supplied')

In [62]:
raw_val = pd.read_csv(f'{Path.cwd() / "com_names_sme 1.csv"}', dtype={"com_num":str})

In [63]:
print(raw_val["com_num"].to_list())

['15073164', '13522064', '11006939', 'SC606050', '11303802', '05914136', '04494986', '02537158', 'SC313991', '02871100', '01382560', '04427981', '14502415', '02591631', '14428804', '15081740', '05210908', '09102217', '00829173', '01941022', '01952156', '00851579', '08283517', '10339143', '03606467', '02318517', '01852173', '13138542', '00805326', '13802242', '02184955', '09536715', 'SC412218', '02407980', '10480357', '01030234', '04635689', '03093541', '07909447', '09712492', '00263728', '06991687', '03242800', '03079224', '06383456', '07051447', '01816008', '05179519', '06122882', '00899832', '02396957', '10561154', '01636551', '00641164', '02408030', '13784047', '05180993', '00784285', '02306031', '02302474', '04372047', 'SC287325', '04656696', '07390480', '07390512', '15092367', '09646807', '15884314', '13984698', '13925097', '14624244', '15762125', '13315396', '15295014', '10715295', '14652281', '15103868', '08684770', '13014456', '13261308', '11126054', '13999081', '08697873', '14771011', '15947090', '06508401', '11563104', '10655307', '10709533', '11383732', '14657587', '04971465', '12935215', '15609041', '07696247', '07083013', '13563517', '14529850', '11380785', '15953465', '10770530', '13979577', '14692988', '13931175', '12585238', '15387949', '11330173', '13144123', '06325879', '11895018', '12713508', '15438057', '09996763', '09530554', '09216993', '15236922', '15514576', '13834625', '13873404', 'SC688109', '12911325', '11000005', '13718084', '08005331', '12804393', '11943499', '14617904', '12498226', '12625805', '12875287', 'SC693176', '15999371', '13830655', '13830660', '14826279', '12539414', '14370234', '12628925', '14694545', '10510951', '13609318', '14963663', '09988464', '14108726', '15100940', '12970406', '15289250', '11599867', '15013489', '07894293', '14590431', '00847998', '03107220', 'SC157855', '04428328', '07405600', '06477864', '06449984', '02571767', '11366346', '00984706', '05152381', '09658601', '16071224', '15333577', '07835499', '14211409', '00559274', '11651868', '08474973', '10985049', '08027318', '15809180', '11168742', '11064518', '11327905', '11957800', '07520428', '09009954', '09285861', '12123939', '11379902', '10037888', '04650683', '01796543', '14469724', '05317581', '14846709', '12254238', '03352798', '10313284', '10312606', '11562254', '13892343', '11644717', '01664263', 'SC234078', '04763606', '08897154', '02921121', '13212574', '08222874', '10900255', '08560508', '00398742', '13887405', '09552596', '02277759', 'SC409169', '14506576', '08195677', '13933356', '12144920', '12829618', '13616605', '08281036', '10753807', '13710113', '01022904', '11326215', '07211105', '14996480', '10633682', '10037712', '08315563', '01359445', '12606821', '04873008', '14687724', '04250076', '12333689', '15517118', '14430354', '07629726', '13142517', '09103886', '14962947', '09814586', '13280774', '15625907', '06317150', '09155811', '10823560', '09282629', '06132185', '13374839', '08591892', '15522996', '03792602', '11475122', '13650620', '15466646', '14594505', '15929568', '08171261', '14996275', '15330717', 'NI681477', '12984661', '13783672', '12722622', '11958020', '11482767', '07081588', '10060151', '15894278', '05934639', '13013116', '05792886', '12193406', '08404782', '14116558', '09798724', '11789237', '03874318', '15739741', '13809345', '14476786', '10233141', '10461207', '12564449', '10216247', '15974595', '09505246', '08640589', '11651330', '14236281', '14761754', '12217260', '13890836', '09648517', '12504216', '06820890', '13292503', '14597534', '13278750', '10523264', '12060582', '10879289', '14152565', '14102081', '13795157', '13098797', '13194784', '11340969', '05516484', '11177567', '09789528', '10562404', '06834192', '03203694', '10219186', '15018557', 'SC693990', '09490689', '15466179', '04927461', '03771248', '05428049', '13508120', '15358890', '15953189', 'SC708331', '10166908', '06902128', '05066650', '03927100', '04981899', '04704445', '14404154', 'SC207149', '15867982', '05085708', 'SC709312', 'SC500562', '10153754', '15011725', '10286992', '14267837', '05404147', '12011923', '14298382', '10766525', '12375065', '14722658', '08230302', '14516354', '04817966', '14326667', '11161427', '10654937', '10833082', '12370791', '15092164', '14083895', 'SC759997', '16273898', '00084968', '00093607', '06948610', '12410702', '14660960', '08347137', '10627591', '06589669', '04143196', '06191664', '13603605', '15251187', '00103598', '05062842', '00158345', '11010691', '15886263', '13603665', '00215235', '00222139', '00224382', '00236319', '07921093', '13603668', '00323880', '00339806', '00361265', '00381000', '04793490', '00444134', '00581048', '00604167', '00654701', '00675273', '04037767', '00697522', '15831213', '12774909', '15824051', '11941798', '15714422', '15434477', '05350501', '04621729', '14494746', '14943257', 'SC769731', '11164411', '13968565', '14999288', '13037433', '10969306', '00717814', '00744999', '14461227', '00783197', '11012273', '00848288', '14232463', '11908509', '14717887', '00968401', '00995662', '11859240', '14504577', '14334950', '09251203', '08936412', '09905985', '02689059', '12091097', '15605617', '13152885', '08331243', '09565554', '14031897', '14654002', '11069747', '13071624', '12972095', '04548746', '05046984', '01000654', '08042532', '11133481', '09922780', '01014273', '01021314', '01034726', '01059925', '01071506', '06483453', '15284392', '15859763', '15318856', '12217080', '14865751', '14304831', '10569921', '12502324', '01225347', '01230630', '01237850', '14321857', '01362414', '01363682', '08489103', 'SC752973', '15116897', '07614766', '15722170', '15777900', '14667305', '01520873', '13475289', '08567248', '15486486', '06723968', '11597565', '03865815', '13925967', '01679183', '01741288', '08616479', '01848714', '01853894', '01906302', '15693871', '01950105', '01970767', '14035130', '13570524', '08294893', '12332987', '09823129', '15077776', '14664735', '15845952', '09076447', '13028664', '13717855', '14726325', '04575460', 'SC605941', '12984310', '14651121', '02007033', '02015685', '02023610', '14121741', '15350277', '12885741', '02077870', '04161880', '14268752', '09238548', '16122085', '09546021', '12768108', '14966029', 'SC699219', '02339455', '02384595', '02398211', '02403363', '02426469', '02512908', '02582802', '02584243', '02590293', '07594425', '02665932', '14448983', '02713854', 'SC461603', '02852465', '02942001', '02943850', '02969355', '02993086', '13992360', '15536677', '13736257', '15090301', '04638000', '15850031', '03596351', '12984467', '03022595', '14572464', '13758926', '15046690', '03075817', '14280689', '03126585', '07247717', '04172945', '13163445', '03237485', '03392200', '14021963', '03645227', '03655200', '03658945', '03668709', '03710226', '03713160', '03734192', '03804007', '03834707', '13736112', '03979297', '11190259', '13918444', '14101133', '12986827', 'NI684591', '14787759', '04108657', '04150553', '04183652', '04190396', '13848179', '13819831', '04319156', '15082855', '04468077', '04491243', '04505884', '04512614', '04725657', '04776217', '04815255', '13452760', '04871850', '15954903', '15988371', '14528942', '05816438', '08303224', '14192044', '05406089', '11996296', '14849180', '05107560', '12771137', '05195050', '13352770', '05217379', '05222736', '05335912', '05477222', '10134463', '05527459', '05696892', '05748280', '05765389', '05931896', '07644803', '05690372', '15193273', '06187904', '14871052', '06228581', '06349133', '06373491', '06376775', '06377227', '06673324', '06674132', '06856364', '06888749', '06911978', '06938741', '10902232', '09526374', 'NI664888', 'NI664670', '06269491', '14080349', '12407929', '08080845', '09897899', '15221685', '11194121', '12790074', '07027135', '09000122', '07131504', '07145996', '08162451', '07280246', '05410907', '07537994', '07539116', '07626968', '07640248', '07650977', '09536159', '07716741', '07737281', '08757710', '07866085', '07973118', '15612130', '13310436', '06871257', '12557058', '14686619', '06230514', '07501972', '13803246', '07214099', '02774274', '06616307', '04780617', '10144539', '05949701', '15115349', '08627197', '12711826', '08122065', '08143460', '08174806', '15948314', '08241526', '08268471', '08304816', '08315001', '08384624', '08610586', '08736305', '08868871', 'SC457356', '12293612', '06428331', '16397291', '08510018', '09000522', '15322753', '12681744', '14013845', '11228017', '09194564', '09227276', '09349330', '09470396', '09477781', '09588692', '09591088', '15297835', 'SC750271', '14859374', '12964800', '10186883', '12604852', '11242269', '14818023', 'SC760490', '15151063', '14666334', '12952119', '11791981', '13634095', '14539526', '12508537', '14172187', '15747986', '13393883', '14184093', '15629377', '14056537', '13552957', '15006957', '11702261', '13433668', '15436104', '10521658', '15864505', '14368404', '14641266', '03267340', '13306715', '10598676', '10506953', '11552381', '04971040', '10973552', '03764767', '01039922', '04920334', '02616923', '15701434', '01318410', '14447681', '11631062', '10734448', '08708032', '13324185', '04672682', '05180391', '13738610', '07895898', '11248662', '09622407', '15078935', '12556964', '07338821', '14549635', '02131069', '03154104', '12895685', '12044781', '03204179', '07804210', '03192025', 'SC701045', '08248201', '15479510', '07641845', '11330754', '05220884', '06946034', '09859558', '09589011', '09083000', '01951219', '10870931', '07394914', '13464624', '01816303', '10766869', '10040694', '12093465', '07385792', '15499571', '06300776', '12891037', '05659194', '04343758', '13112644', '14130376', 'SC506330', '14018957', '04553040', '05183413', '04806378', '05682396', '09343608', '14975105', '10405429', '16091036', '06993587', '07852066', '13805664', '06931087', '11456427', '14968336', 'NI727080', '07865058', '14231681', '14802548', '10317566', '04767688', '03234519', '09635732', '04201623', '05379198', '12132717', 'SC362440', '10933445', '11378396', '03737626', '02643063', '12115906', '12216215', '04130235', '09036482', '03646386', '07013419', '15810222', '12905136', '09742021', '09631616', '11716578', '04424336', '02121226', '13641025', '06052134', '12715687', '03853913', '02790881', '03844623', '01871001', '14483098', '06914222', '06619078', '03321447', '07234058', '11675713', '03132878', '10734436', '13872897', '11413501', '04550264', '09887851', '09413842', '05976847', '12111458', '02702163', '09494992', '05750963', '08514278', '03296088', '13214466', '11434733', '02081934', 'SC471828', '10142683', '14923886', '08855280', '11849897', '12147219', '05769742', '10692898', '14619725', '08922349', '14298108', '11373776', '06570868', '09938437', '05241596', '10539362', '06628707', '15663331', '01288154', '07569919', '07490194', '09272783', '10801538', '03142203', '11084051', '15534121', '12764051', '11800782', '01872607', '02539475', '15668367', '15546912', '02419669', '07101478', '04539953', '01649850', '13685331', '04410426', '12106770', '08185784', '10128730', '02397889', '02584287', '03394142', '07642507', '05581050', '12280255', '08376324', '10440173', '15235538', '13189415', '13466674', '14993448', '08755431', '06666580', '12749223', '07984465', '13429202', 'SC828121', '07639451', '10559797', '08318704', '13232258', '01864678', '06493714', '15309314', '10156949', '14573201', '12713602', '07251584', '13608023', '03010608', '15493703', '14006429', '15602112', '10887711', '06591085', '09730803', '09908329', '09092828', '13419739', '05780123', '13750215', '03042765', '10607732', '11169337', '03334864', '13984713', '10926177', '05818267', '13021273', '03341473', '10644868', '10791465', '13095603', '03503752', '14328522', '08559114', '01827323', '09368417', '03789845', '11985844', '04482920', '08702897', '14502620', '02903909', '04094532', '05475732', '13185440', '06296318', '04136364', '07793825', '10297543', '14085347', '10994209', '04912184', '14255324', '14542568', '12745322', '13450891', '13415495', '15175753', '16649564', '15522452', '15851225', '13641701', '12768734', '08001207', '14324270', '14470048', '03680601', '09227989', '04303582', '08405927', '02377614', '05037210', '13094482', '11344318', '10477971', '08892307', '09171644', '10313140', '15708824', '13935052', '01818467', '11210494', '04627597', '07136451', 'SC632576', '08396141', '12066082', '07934916', '06371497', '14206913', '12893742', '13295937', '11657522', '11789968', '10047169', '15750079', '15261583', '13897368', '09398174', '09275090', '08476375', '10034165', '06620391', '11193054', '13298270', '13962599', '01576762', '07848748', '12647444', '03407953', '01919487', '03824713', '13954369', '10770429', '04167478', '04445195', '12591407', '07544404', '15802010', '15531019', '08885977', '02175946', '15094414', '08446898', '13455253', '02320423', '11854946', '14452468', '10573122', '14691934', '11954950', '12541868', '01583386', '10332472', '06620965', '05317463', '03394685', '02430202', '02532420', '02262499', '04300274', '04968969', '04667839', '09657103', '14559143', '13536937', '10751170', '15011311', '15563155', '04002803', '06798239', '14839471', '11113714', '16254012', '15729310', '15389378', '07459692', '08576021', '11157354', '12912382', '11002238', '09493592', '06696406', '03931182', '14440016', '10923603', '04396497', '03005873', '15753237', '13298746', '11825372', '03302554', '15643249', '06900256', '12447177', '03201238', '09300732', '01683636', '15184931', '11583378', '02151200', '11562467', '08605124', '05834221', '01674160', '10661479', '09082250', '03838175', '05653902', '14242419', '02873850', '11136386', '05312320', '08737035', '04887195', '08287045', '11046599', '12718108', '02948019', '10850937', '04251181', '05927371', '13819351', '08058538', '13611427', '13140847', '03246485', '08609392', '09360013', '14575137', '11474463', '10789796', '02468599', '02535620', '06709480', '07947662', '14925958', '02837164', '12411378', '02175660', '04192148', '05856012', '10075255', '13394741', '02224659', '03314056', '09126740', '11826851', '06017972', '12045321', '14051034', '11140823', '12438194', '10596741', '04837228', '13611766', '15293786', '15303133', '04200875', '14367279', '09172696', '13346692', '14686352', '04243824', '10665470', '09809014', '13466669', '07880701', '11763220', '08643008', '09161383', '08684219', '08510434', '15215659', '09994708', '12642265', '13949794', '09901755', '12521337', '14434570', '13648865', '10165300', '11499901', '10573704', '13436026', '13433039', 'NI610891', '08656332', '13462242', '13434545', 'SC635877', 'SC137429', '12188881', '14776847', '06679162', 'SC755470', '03354877', '11065168', '01990814', '14898550', '11770231', '09990983', '13776363', '06758337', '05882202', '10608570', '14792175', '15838941', '15301518', '01768306', '12605098', '15440667', '05065132', '11743146', 'SC456142', '08615906', '07248368', '14422615', '03592458', '06605833', '13831401', '12281952', '15266382', '16011977', '14599381', '11909072', '09320544', '07050097', '06086801', '13453943', '09914077', '10725462', '15027157', '06959514', '14900319', '14609378', '15746044', '14384486', '15253811', '06307620', '02675092', '06737211', '12919226', '09559685', '11265516', '14572987', '06732954', 'SC722062', '08861843', '14676673', '01739606', '09045957', '05304778', '12064879', '02490844', '01927265', '06322834', '07988571', '08467155', '15263913', '12447234', '07025653', '15061787', 'SC667295', '11898233', '01236165', '07715413', '05997405', '11041206', '09339921', '15211025', '12716484', '02274558', '01643887', '01929265', '13740304', '13170188', '11091044', '01760643', '11598905', '13496696', '08384969', '10949613', '15722577', '08254449', '09191550', '09261355', '13575395', '12027727', '11549900', '15320074', '06424598', '11923444', '12895565', '15441532', '14362311', '08623011', '14622894', '09920796', '06130158', '08399206', '01850583', '15345934', '02400140', '12005442', '07278023', '08736906', '05150900', '08947327', '15852362', '14270428', '15946033', '13590618', '05101604', '01979518', '10246685', '06556181', '02445507', '12248599', '09606267', '08792981', '07203806', '13022453', '14102775', '13385617', '14847966', '05786491', '02391317', '08089667', '10260970', '08304285', '13971030', '11526540', '14318474', '15876367', '11813783', '11885688', '12763484', '09570072', '12258787', '08224155', '14058203', '11753812', '10709531', '09112904', '08998497', '08878498', '08309994', '08309992', '08310010', '13884489', '13510023', '12104628', '12797678', '12175840', '15002061', '07907644', '12175947', '10176664', '11878679', '07990874', '07722410', '07588537', '12675397', '15628828', 'NI675897', '12310259', '12829628', '15741459', '11955974', '14974440', '16000824', '07427527', '06554958', 'SC278997', '09788101', '12207641', 'SC435723', 'SC401207', '10738692', 'NI658140', '08911697', '08170531', 'SC753677', '14939400', '15474813', '15029080', '11655797', '13030562', 'NI688302', '13821228', '14338553', 'SC777453', '03240248', '14216679', '07794048', '02309809', '08252384', '06953587', '07030382', '13119738', '03838371', 'SC824859', '07407449', '13544114', '13885750', '09015601', '05813927', '16053382', '15459849', '14925999', '11281240', '01050932', '15157107', '11221035', '07638927', '03347568', '11943812', '08327125', '06927510', '08386131', '06633218', '04703899', '07701697', '07712916', '06398302', '13044154', '08782199', '07963398', '07261036', '03012380', '04099594', '11852749', '13491283', '03866952', '11107277', '10064628', '06793590', '14071360', '13590079', '10682956', '02573141', '02543028', '05265446', '07129513', '12098691', '13919247', '11655717', '06909292', '07691776', '14164276', 'SC385818', '06451182', '13788905', '07878097', '10489121', '13131238', '14391685', '12532564', '12837860', 'SC361874', '01339220', '15976104', '09441887', '06859263', '06020171', '06660591', '13880155', '07863450', '03009049', '10721611', '06760882', '06989675', '06165869', '05744450', '03482638', '04701083', '11635374', '09812506', '01103504', '09147866', 'SC504096', '15836406', '04683525', '12910873', '05275397', '01116627', '13221283', '11287277', '04574745', '11314883', '05212273', '06836934', '02582558', '11377781', '11390593', 'SC632332', '05034164', '02867191', '02578166', '10931015', '02715078', '10736475', '07417220', '09649424', '03180128', '03394170', '07352303', '03886183', '12778817', '06791112', '08530109', '15883114', '09759604', '15062683', '15165045', '08152595', '07687332', '01225600', '02391373', '01263710', '00737701', '01442519', '07826983', '10092475', '04821418', '03294325', '07382398', '10877400', '12372250', '12849570', '01648377', '09618037', '08173407', '03056842', '14761585', '14609493', '14189196', '13643787', '14070154', '03241667', '05413511', '01693070', '08924729', '08589702', '09767191', '01807880', '02664198', '06697299', '08451890', '11404585', '07409235', '03480146', '11789950', '12957433', '07692611', '10293453', '13014138', '13145620', '09005855', '14204447', '12593130', '07680110', '07681317', '07380131', '11599267', '13545349', '09353164', '13837177', '05623663', '08212864', '08322218', '02883984', '08749839', '09416082', '05719479', '09544664', '13421748', '07838604', '09904874', '04614198', '07352835', '10946900', '13823728', '13745749', '14518262', '09550098', '08866639', '07269333', '07073003', '09984571', '05885972', '12394465', '11791683', '07272082', '06542841', 'SC425920', '06858948', '07990251', '15200584', '03961551', '05316770', '06630420', '12367614', '07734764', '13664272', '15753300', '13176022', '11024824', '11632017', '12873502', '05704015', '10820370', '13505478', '02634239', '11058365', '13702388', '05783410', '09449322', '11947979', '10654482', '14898116', '06734074', '05751564', '12541753', '08143257', '02634198', '04157547', '14916605', '14397169', '15299027', '10431073', '13516039', '11198941', '10129150', '15868266', '11184865', '02863893', '09485510', '08556700', '14085209', '08733815', '08061951', '13086947', '13332518', '06759604', '07483754', '03890131', '133973

In [64]:
result = []
for i in raw_val["com_num"]:
    conn = sql.connect(Path.cwd().parent / os.getenv("DB_URL"))
    cursor = conn.cursor()

    cursor.execute("SELECT c.company_type, c.town, c.county, c.post_code FROM companies c WHERE c.company_id = ?", (i,))
    out = cursor.fetchall()

    com_type, town, county, post_code = out[0] if out else (None, None, None, None)
    result.append((com_type, town, county, post_code))

result

[('Private Limited Company', 'POTTERS BAR', 'HERTFORDSHIRE', 'EN6 2DA'),
 ('Private Limited Company', 'LONDON', 'GREATER LONDON', 'WC2H 9JQ'),
 ('Private Limited Company', 'EDENBRIDGE', None, 'TN8 5NF'),
 ('Private Limited Company', 'ABERDEEN', None, 'AB11 7SY'),
 ('Private Limited Company', 'GREAT WAKERING', 'ESSEX', 'SS3 0GW'),
 ('PRI/LTD BY GUAR/NSC (Private, limited by guarantee, no share capital)',
  'CROYDON',
  'SURREY',
  'CR0 2RF'),
 ('Private Limited Company', 'BOLTON', None, 'BL2 1HQ'),
 ('Private Limited Company', 'LONDON', None, 'E1 7AA'),
 ('Private Limited Company', 'GLENROTHES', None, 'KY6 2RU'),
 ('Private Limited Company', None, None, 'W12 8LA'),
 ('Private Limited Company', 'NORWICH', None, 'NR2 2AL'),
 ('Private Limited Company', 'WISBECH', 'CAMBRIDGESHIRE', 'PE13 1EH'),
 ('Private Limited Company', 'CORBY', None, 'NN17 2JY'),
 ('PRI/LTD BY GUAR/NSC (Private, limited by guarantee, no share capital)',
  'ST ASAPH',
  'DENBIGHSHIRE',
  'LL17 0RE'),
 ('Private Limited Company', 'EDGWARE', None, 'HA8 8BN'),
 ('Private Limited Company', 'LONDON', None, 'E5 0NF'),
 ('Private Limited Company', 'LONDON', None, 'NW7 2DQ'),
 ('Private Limited Company', 'SWANSCOMBE', 'KENT', 'DA10 1ET'),
 ('Private Limited Company', 'SUNBURY-ON-THAMES', 'MIDDLESEX', 'TW16 5LB'),
 ('Private Limited Company', 'LONDON', None, 'E4 8EE'),
 ('Private Limited Company', 'TORQUAY', None, 'TQ1 3NT'),
 ('Private Limited Company', 'BECKENHAM', 'KENT', 'BR3 5BZ'),
 ('Private Limited Company', 'MITCHAM', None, 'CR4 4AB'),
 ('Private Limited Company', 'LONDON', None, 'W1F 7TA'),
 ('Private Limited Company', 'ILFORD', None, 'IG2 6UF'),
 ('Private Limited Company', 'FELTHAM', 'MIDDLESEX', 'TW14 0SL'),
 ('Private Limited Company', 'WESTBURY ON TRYM', 'BRISTOL', 'BS10 6LW'),
 ('Private Limited Company', 'WREXHAM', None, 'LL13 9QQ'),
 ('Private Limited Company', 'COLWYN BAY', 'CONWY', 'LL29 8PE'),
 ('Private Limited Company', 'GLOUCESTER', None, 'GL3 2BN'),
 ('PRI/LTD BY GUAR/NSC (Private, limited by guarantee, no share capital)',
  'MERSEYSIDE',
  None,
  'L36 7XG'),
 ('Private Limited Company', 'GRAYS', None, 'RM16 4RT'),
 ('Private Limited Company', 'ABERDEEN', None, 'AB22 8TJ'),
 ('Private Limited Company', 'HATFIELD', None, 'AL10 0LJ'),
 ('Private Limited Company', 'HEMEL HEMPSTEAD', 'HERTFORDSHIRE', 'HP2 4PP'),
 ('Private Limited Company', 'ALTRINCHAM', 'CHESHIRE', 'WA14 2DT'),
 ('Private Limited Company', 'DRY DRAYTON', 'CAMBRIDGESHIRE', 'CB23 8AT'),
 ('Private Limited Company', 'MAIDENHEAD', 'BERKSHIRE', 'SL6 7QN'),
 ('Private Limited Company', 'DORKING', None, 'RH5 4BQ'),
 ('Private Limited Company', 'BOREHAMWOOD', None, 'WD6 1EB'),
 ('Private Limited Company', 'MANCHESTER', None, 'M12 5NG'),
 ('Private Limited Company', 'BLACKPOOL', 'LANCASHIRE', 'FY4 2NY'),
 (None, None, None, None),
 ('Private Limited Company', ' UPLYME', 'DORSET', 'DT7 3SU'),
 ('PRI/LTD BY GUAR/NSC (Private, limited by guarantee, no share capital)',
  'CAMBRIDGE',
  'CAMBS',
  'CB2 1JP'),
 ('Private Limited Company', 'BRISTOL', None, 'BS16 9PE'),
 ('Private Limited Company', 'LONDON', None, 'SW7 4AG'),
 ('Private Limited Company', 'CHESTER LE STREET', 'CO DURHAM', 'DH3 4AN'),
 ('Private Limited Company', 'ROCHFORD', 'ESSEX', 'SS4 1AJ'),
 ('Private Limited Company', 'TEDDINGTON', 'MIDDLESEX', 'TW11 8QT'),
 ('Private Limited Company', 'KINGSBRIDGE', 'DEVON', 'TQ7 1LR'),
 ('Private Limited Company', 'BIRMINGHAM', None, 'B17 0NL'),
 ('PRI/LTD BY GUAR/NSC (Private, limited by guarantee, no share capital)',
  'WHITBY',
  'NORTH YORKSHIRE',
  'YO21 3DQ'),
 ('Private Limited Company', 'CHATHAM', None, 'ME4 6BB'),
 ('Private Limited Company', 'PUDSEY', None, 'LS28 7DG'),
 ('Private Limited Company', 'SOUTHAMPTON', None, 'SO18 5DG'),
 ('Private Limited Company', 'BROMLEY', 'KENT', 'BR2 9HG'),
 ('Private Limited Company', 'SOUTH CROYDON', None, 'CR2 6AL'),
 ('Private Limited Company', 'GUILDFORD', None, 'GU2 9TY'),
 ('Private Limited Company', 'BRAINTREE', 'ESSEX', 'CM7 1JP'),
 ('Private Limited Company', 'WARWICKSHIRE', None, 'CV34 4EW'),
 ('Private Limited Company', 'GLASGOW', None, 'G41 1HJ'),
 ('Private Limited Company', 'NEWCASTLE UPON TYNE', 'TYNE & WEAR', 'NE1 7RA'),
 ('Private Limited Company', 'CROMER', 'NORFOLK', 'NR27 9JR'),
 ('Private Limited Company', 'CROMER', 'NORFOLK', 'NR27 9JR'),
 ('Private Limited Company', 'LONDON', None, 'N1 7GU'),
 ('Private Limited Company', 'SUDBURY', None, 'CO10 0ZG'),
 ('Private Limited Company', 'GATESHEAD', None, 'NE9 6LA'),
 ('Private Limited Company', 'LONDON', 'GREATER LONDON', 'W1D 1LP'),
 ('Private Limited Company', 'STEVENAGE', 'HERTFORDSHIRE', 'SG2 9QA'),
 ('Private Limited Company', 'LEEDS', None, 'LS1 2BH'),
 ('Private Limited Company', 'BRIGHOUSE', 'WEST YORKSHIRE', 'HD6 1RY'),
 ('Private Limited Company', 'STEVENAGE', None, 'SG2 8PT'),
 ('Private Limited Company', 'LONDON', None, 'EC1V 2NX'),
 ('Private Limited Company', 'LIVERPOOL', None, 'L3 1BP'),
 ('Private Limited Company', 'CHIPPENHAM', 'WILTSHIRE', 'SN15 3HR'),
 ('Private Limited Company', 'STOURBRIDGE', None, 'DY9 0JT'),
 ('Private Limited Company', 'WIMBORNE', 'DORSET', 'BH21 1QE'),
 ('Private Limited Company', 'THORNTON HEATH', 'SURREY', 'CR7 6JB'),
 ('Private Limited Company', 'BRIGHTON', None, 'BN1 5NP'),
 ('Private Limited Company', 'LONDON', None, 'SW8 1EF'),
 ('Private Limited Company', 'PORTSMOUTH', 'HAMPSHIRE', 'PO1 5BX'),
 ('Private Limited Company', 'LEICESTER', None, 'LE19 4SA'),
 ('Private Limited Company', 'BRISTOL', None, 'BS6 5HU'),
 ('Private Limited Company', 'WETHERBY', 'WEST YORKSHIRE', 'LS22 6LP'),
 ('Private Limited Company', 'KINGS LANGLEY', 'HERTFORDSHIRE', 'WD4 8FR'),
 ('Private Limited Company', 'SOUTH MOLTON', 'NORTH DEVON', 'EX36 3LE'),
 ('Private Limited Company', 'BROMSGROVE', 'WORCESTERSHIRE', 'B61 8DN'),
 ('Private Limited Company', 'BRENTWOOD', 'ESSEX', 'CM13 1AB'),
 ('Private Limited Company', 'LONDON', None, 'W1T 4TQ'),
 ('Private Limited Company', 'TENTERDEN', 'KENT', 'TN30 6TU'),
 ('Private Limited Company', 'LONDON', None, 'E20 1HZ'),
 ('Private Limited Company', 'LONDON', None, 'NW1 2EW'),
 ('Private Limited Company', 'LONDON', None, 'EC1V 2NX'),
 ('Private Limited Company', 'LONDON', None, 'SE15 4BQ'),
 ('Private Limited Company', 'LONDON', None, 'E1 6PX'),
 ('Private Limited Company', 'MILDENHALL', 'SUFFOLK', 'IP28 7DE'),
 ('Private Limited Company', 'RADSTOCK', 'SOMERSET', 'BA3 5UZ'),
 ('Private Limited Company', 'GUILDFORD', None, 'GU1 3SA'),
 ('Private Limited Company', 'HARLOW', 'ESSEX', 'CM20 2DB'),
 ('Private Limited Company', 'SAWBRIDGEWORTH', 'HERTFORDSHIRE', 'CM21 9AE'),
 ('Private Limited Company', 'MATLOCK', None, 'DE4 4FF'),
 ('Private Limited Company', 'SIDCUP', 'KENT', 'DA14 4DT'),
 ('Private Limited Company', 'LONDON', None, 'SW16 6NR'),
 ('Private Limited Company', 'LONDON', None, 'SW16 4XD'),
 ('Private Limited Company', 'CANTERBURY', None, 'CT4 6HD'),
 ('Private Limited Company', 'LONDON', None, 'EC2A 4BA'),
 ('Private Limited Company', 'STOURBRIDGE', 'WEST MIDLANDS', 'DY8 1LU'),
 ('Private Limited Company', 'LONDON', None, 'W1B 5AW'),
 ('Private Limited Company', 'CAMBRIDGE', None, 'CB24 6WZ'),
 ('Private Limited Company', 'LONDON', None, 'WC1X 8HN'),
 ('Private Limited Company', 'LONDON', None, 'WC1R 4QH'),
 ('Private Limited Company', 'LEEDS', None, 'LS1 2HL'),
 ('Private Limited Company', 'PONTESBURY', 'SHROPSHIRE', 'SY5 0QB'),
 ('Private Limited Company', 'SLOUGH', 'BERKSHIRE', 'SL1 6AE'),
 ('Private Limited Company', 'LONDON', None, 'SW13 9HH'),
 ('Private Limited Company', 'LEICESTER', None, 'LE8 8UF'),
 ('Private Limited Company', 'LEIGH-ON-SEA', None, 'SS9 2HL'),
 ('Private Limited Company', 'LEIGH-ON-SEA', None, 'SS9 2HL'),
 ('Private Limited Company', 'GLASGOW', None, 'G31 1SZ'),
 ('Private Limited Company', 'LONDON', None, 'E11 4EA'),
 ('Private Limited Company', 'HAILSHAM', None, 'BN27 1DW'),
 ('Private Limited Company', 'HUDDERSFIELD', None, 'HD1 1QZ'),
 ('Private Limited Company', 'BLACKPOOL', 'LANCASHIRE', 'FY3 8LT'),
 ('Private Limited Company', 'LEICESTER', None, 'LE7 2HB'),
 ('Private Limited Company',
  'WESTON-SUPER-MARE',
  'NORTH SOMERSET',
  'BS23 1JP'),
 ('Private Limited Company', 'WOODBRIDGE', 'SUFFOLK', 'IP13 8LR'),
 ('Private Limited Company', 'LEEDS', None, 'LS18 5BP'),
 ('Private Limited Company', 'LEEDS', None, 'LS14 1FB'),
 ('Private Limited Company', 'CHELTENHAM', None, 'GL53 0AN'),
 ('Private Limited Company', 'EDINBURGH', None, 'EH12 9EG'),
 ('Private Limited Company', 'LONDON', None, 'SE1 1JA'),
 ('Private Limited Company', 'LONDON', None, 'SE4 2RS'),
 ('Private Limited Company', 'LONDON', None, 'SE4 2RS'),
 ('Private Limited Company', 'EAST GRINSTEAD', 'WEST SUSSEX', 'RH19 3EL'),
 ('Private Limited Company', 'WALTHAM ABBEY', None, 'EN9 1FL'),
 ('Private Limited Company', 'LONDON', None, 'NW6 2DP'),
 ('Private Limited Company', 'GRAYS', None, 'RM17 5NL'),
 ('Private Limited Company', 'SOLIHULL', None, 'B94 5LW'),
 ('Private Limited Company', 'PUTNEY', 'LONDON', 'SW15 2SH'),
 ('Private Limited Company', 'BRIGHTON', 'EAST SUSSEX', 'BN1 9SB'),
 ('Private Limited Company', 'CHELTENHAM', None, 'GL52 6QP'),
 ('Private Limited Company', 'CHELTENHAM', None, 'GL52 6QP'),
 ('Private Limited Company', 'PEASMARSH', 'SURREY', 'GU3 1AF'),
 ('Private Limited Company', 'LONDON', None, 'E16 2XF'),
 ('Private Limited Company', 'MILTON KEYNES', 'BUCKINGHAMSHIRE', 'MK5 8FR'),
 ('Private Limited Company', 'NEWCASTLE UPON TYNE', None, 'NE6 5UY'),
 ('Private Limited Company', 'LONDON', None, 'E15 2HB'),
 ('Private Limited Company', 'LONDON', None, 'EC1V 2NX'),
 ('Private Limited Company', 'BILLINGSHURST', 'WEST SUSSEX', 'RH14 9JA'),
 ('Private Limited Company', 'LONDON', None, 'N11 3DT'),
 ('PRI/LTD BY GUAR/NSC (Private, limited by guarantee, no share capital)',
  'LONDON',
  None,
  'W1T 3BL'),
 ('Private Limited Company', 'HARROW', 'MIDDLESEX', 'HA1 1BH'),
 ('Private Limited Company', 'CLYDEBANK', None, 'G81 6LD'),
 ('Private Limited Company', 'CORBY', 'NORTHAMPTONSHIRE', 'NN17 5JG'),
 ('Private Limited Company', 'ROTHERHAM', None, 'S66 2NR'),
 ('Private Limited Company', 'LONDON', None, 'E2 6GH'),
 ('Private Limited Company', 'CUMBRIA', None, 'CA3 8RR'),
 ('PRI/LTD BY GUAR/NSC (Private, limited by guarantee, no share capital)',
  'WATFORD',
  None,
  'WD24 7NE'),
 ('Private Limited Company', 'DERBY', None, 'DE1 2BU'),
 ('Private Limited Company', 'BOWNESS-ON-WINDERMERE', None, 'LA23 2JJ'),
 ('Private Limited Company', 'CAMBS', None, 'PE1 5XA'),
 ('Private Limited Company', 'BERKHAMSTED', None, 'HP4 3EB'),
 ('Private Limited Company', 'FERNDOWN', 'DORSET', 'BH22 8PB'),
 ('Private Limited Company', 'LONDON', None, 'SE9 6AR'),
 ('Private Limited Company', 'ROMSEY', 'HAMPSHIRE', 'SO51 6FU'),
 ('Private Limited Company', 'PLYMOUTH', None, 'PL7 5JX'),
 ('Private Limited Company', 'EXETER', 'DEVON', 'EX2 5WS'),
 ('Private Limited Company', 'LONDON', None, 'E17 6BU'),
 ('Private Limited Company', 'MANCHESTER', None, 'M2 5NS'),
 ('Private Limited Company', 'DRONFIELD', None, 'S18 7WG'),
 ('Private Limited Company', 'WILLINGDON', 'EAST SUSSEX', 'BN22 0HR'),
 ('Private Limited Company', 'LONDON', None, 'E3 5LX'),
 ('Private Limited Company', 'LONDON', None, 'EC3V 9DU'),
 ('Private Limited Company', 'DERBY', 'DERBYSHIRE', 'DE21 4BJ'),
 ('Private Limited Company', 'HORSHAM', None, 'RH12 4HT'),
 ('Private Limited Company', 'LONDON', None, 'N1 7GU'),
 ('Private Limited Company', 'ROCHESTER', 'KENT', 'ME2 4BH'),
 ('Private Limited Company', 'LONDON', None, 'E1 4HQ'),
 ('Private Limited Company', 'WALTHAM CROSS', None, 'EN8 8AG'),
 ('Private Limited Company', 'LONDON', None, 'NW10 7TR'),
 ('Private Limited Company', 'BOLTON', 'LANCASHIRE', 'BL5 3QJ'),
 ('Private Limited Company', 'PETERBOROUGH', None, 'PE2 6FY'),
 ('Private Limited Company', 'ROCHDALE', 'LANCASHIRE', 'OL11 5BT'),
 ('Private Limited Company', 'ROCHDALE', 'LANCASHIRE', 'OL12 6AA'),
 ('Private Limited Company', 'PETERSFIELD', None, 'GU31 4AG'),
 ('Private Limited Company', 'CLEVEDON', 'NORTH SOMERSET', 'BS21 7NL'),
 ('Private Limited Company', 'HARROW', None, 'HA1 1BQ'),
 ('Private Limited Company', 'NOTTINGHAM', None, 'NG16 6NS'),
 ('Private Limited Company', 'SOUTHEND-ON-SEA', None, 'SS1 1BH'),
 ('Private Limited Company',
  'LYNCH WOOD, PETERBOROUGH',
  'CAMBRIDGESHIRE',
  'PE2 6FT'),
 ('Private Limited Company',
  'LYNCH WOOD, PETERBOROUGH',
  'CAMBRIDGESHIRE',
  'PE2 6FT'),
 ('Private Limited Company', 'LONDON', None, 'SE1 0HS'),
 ('Private Limited Company', 'LONDON', None, 'W1W 7LT'),
 ('Private Limited Company', 'LONDON', None, 'W1W 7LT'),
 ('Private Limited Company', 'WHITEHAVEN', None, 'CA28 8YD'),
 ('Private Limited Company', 'ABERDEEN', None, 'AB15 7RY'),
 ('Private Limited Company', 'WADHURST', 'EAST SUSSEX', 'TN5 6QE'),
 ('Private Limited Company', 'BRAINTREE', 'ESSEX', 'CM7 1HU'),
 ('Private Limited Company', 'LEEDS', 'WEST YORKSHIRE', 'LS13 4AW'),
 ('Private Limited Company', 'LINCOLN', None, 'LN1 3EW'),
 ('Private Limited Company', 'SHEFFIELD', None, 'S9 1XA'),
 ('Private Limited Company', 'CARDIFF', None, 'CF72 8NG'),
 ('Private Limited Company', 'SOLIHULL', 'WEST MIDLANDS', 'B90 2QB'),
 ('Private Limited Company', 'PYTCHLEY,', 'KETTERING, NORTHANTS', 'NN14 1EW'),
 ('Private Limited Company', 'BRIGHTON', None, 'BN2 9QA'),
 ('Private Limited Company', 'CARDIFF', None, 'CF11 9LJ'),
 ('PRI/LTD BY GUAR/NSC (Private, limited by guarantee, no share capital)',
  'COLCHESTER ESSEX',
  None,
  'CO1 1HF'),
 ('Private Limited Company', 'EDINBURGH', None, 'EH10 5LZ'),
 ('Private Limited Company', 'NEWQUAY', 'CORNWALL', 'TR7 1DX'),
 ('Private Limited Company', 'THORNABY', None, 'TS17 6PF'),
 ('Private Limited Company', 'BROMLEY', None, 'BR1 3PZ'),
 ('Private Limited Company', 'LONDON', None, 'W1W 6QT'),
 ('Private Limited Company', 'STOCKPORT', None, 'SK7 5PA'),
 ('Private Limited Company', 'HOVE', None, 'BN3 5FN'),
 ('PRI/LTD BY GUAR/NSC (Private, limited by guarantee, no share capital)',
  'SLOUGH',
  'BERKSHIRE',
  'SL1 3BX'),
 ('Private Limited Company', 'MALDON', 'ESSEX', 'CM9 8LZ'),
 ('Private Limited Company', 'HALIFAX', 'WEST YORKSHIRE', 'HX1 1SP'),
 ('Private Limited Company', 'KIDDERMINSTER', 'WORCESTERSHIRE', 'DY10 1JR'),
 ('Private Limited Company', 'CARDIFF', None, 'CF14 3AY'),
 ('Private Limited Company', 'WEYBRIDGE', 'SURREY', 'KT13 8DE'),
 ('Private Limited Company', 'LONDON', None, 'N1 7GU'),
 ('Private Limited Company', 'ALDERSHOT', 'HAMPSHIRE', 'GU11 3DP'),
 ('Private Limited Company', 'LYTHAM ST ANNES', 'LANCASHIRE', 'FY8 1QG'),
 ('Private Limited Company', 'LONDON', None, 'SE14 6QL'),
 ('Private Limited Company', 'GLOUCESTER', None, 'GL19 3JZ'),
 ('Private Limited Company', 'PLYMOUTH', None, 'PL6 6BX'),
 ('Private Limited Company', 'TAMWORTH', 'STAFFORDSHIRE', 'B79 7RB'),
 ('Private Limited Company', 'LINCOLN', None, 'LN1 4BJ'),
 ('Private Limited Company', 'LEEDS', 'WEST YORKSHIRE', 'LS10 1JQ'),
 ('Private Limited Company', 'NR IPSWICH', 'SUFFOLK', 'IP6 9SG'),
 ('Private Limited Company', 'LEEDS', 'WEST YORKSHIRE', 'LS18 5BJ'),
 ('Private Limited Company', 'BEXLEYHEATH', None, 'DA7 4PP'),
 ('Private Limited Company', 'TELFORD', 'SHROPSHIRE', 'TF2 9NT'),
 ('Private Limited Company', 'CLITHEROE', None, 'BB7 9GL'),
 ('Private Limited Company', 'ST. NEOTS', None, 'PE19 6HH'),
 ('Private Limited Company', 'LONDON', None, 'E6 1AA'),
 ('Private Limited Company', 'BRISTOL', None, 'BS9 3HQ'),
 ('Private Limited Company', 'NOTTINGHAM', None, 'NG9 5BE'),
 ('Private Limited Company', 'BURTON ON TRENT', None, 'DE14 2DH'),
 ('PRI/LTD BY GUAR/NSC (Private, limited by guarantee, no share capital)',
  'LANCASHIRE',
  None,
  'BB9 7LE'),
 ('Private Limited Company', 'NOTTINGHAM', None, 'NG5 4DR'),
 ('Private Limited Company', 'LONDON', None, 'N1 0AF'),
 ('Private Limited Company', 'LONDON', None, 'WC1H 9LG'),
 ('Private Limited Company', 'LONDON', None, 'WC1H 9LG'),
 ('Private Limited Company', 'MANCHESTER', None, 'M27 5SN'),
 ('Private Limited Company', 'COLCHESTER', None, 'CO1 2EB'),
 ('Private Limited Company', 'REDHILL', None, 'RH1 5RP'),
 ('Private Limited Company', 'WARWICK', 'WARWICKSHIRE', 'CV35 8HG'),
 ('Private Limited Company', 'ILFORD', 'ESSEX', 'IG1 4NF'),
 ('PRI/LTD BY GUAR/NSC (Private, limited by guarantee, no share capital)',
  'LONDON',
  None,
  'N1 7GU'),
 ('Private Limited Company', 'LONDON', None, 'SW3 5QP'),
 ('Private Limited Company', 'LONDON', None, 'UB8 2SN'),
 ('Private Limited Company', 'LONDON', 'ENGLAND', 'EC2A 4NE'),
 ('Private Limited Company', 'STAMFORD', None, 'PE9 2YL'),
 ('Private Limited Company', 'RADSTOCK', None, 'BA3 4HP'),
 ('Private Limited Company', 'STANMORE', None, 'HA7 1JS'),
 ('Private Limited Company', 'BALLYCLARE', None, 'BT39 9BG'),
 ('Private Limited Company', 'BLACKPOOL', None, 'FY4 5FS'),
 ('PRI/LTD BY GUAR/NSC (Private, limited by guarantee, no share capital)',
  'HESSLE',
  None,
  'HU13 9DB'),
 ('Private Limited Company', 'MANCHESTER', 'LANCASHIRE', 'M43 6PT'),
 ('Private Limited Company', 'LONDON', 'GREATER LONDON', 'WC2H 9JQ'),
 ('Private Limited Company', 'CAMBERLEY', None, 'GU15 3PQ'),
 ('Private Limited Company', 'PETERBOROUGH', None, 'PE3 6SR'),
 ('Private Limited Company', 'CHELMSFORD', None, 'CM1 1HT'),
 ('Private Limited Company', 'BARNSLEY', None, 'S74 8JS'),
 ('Private Limited Company', 'PEASE POTTAGE', 'WEST SUSSEX', 'RH11 9UX'),
 ('Private Limited Company', 'CREWE', 'CHESHIRE', 'CW1 3TE'),
 ('Private Limited Company', 'WARRINGTON', None, 'WA4 6NU'),
 ('Private Limited Company', "BISHOP'S STORTFORD", None, 'CM23 2DH'),
 ('Private Limited Company', 'BRISTOL', None, 'BS2 8NX'),
 ('Private Limited Company', 'ABERDARE', None, 'CF44 6RE'),
 ('Private Limited Company', 'PORTSMOUTH', None, 'PO1 4QH'),
 ('Private Limited Company', 'CHIPPENHAM', 'WILTSHIRE', 'SN15 3RS'),
 ('Private Limited Company', 'SUNDERLAND', None, 'SR1 1BU'),
 ('Private Limited Company', 'GRAVESEND', None, 'DA11 0EF'),
 ('Private Limited Company', 'APSLEY WAY', None, 'NW2 7HF'),
 ('Private Limited Company', 'BURY ST. EDMUNDS', None, 'IP28 8DS'),
 ('Private Limited Company', 'OLDHAM', None, 'OL1 4NX'),
 ('Private Limited Company', 'LONDON', None, 'N17 9SJ'),
 ('Private Limited Company', 'LYE', None, 'DY9 8JX'),
 ('Private Limited Company', 'BOLTON', None, 'BL6 7AF'),
 ('Private Limited Company', 'BRADFORD', None, 'BD8 7DT'),
 ('Private Limited Company', 'PLYMOUTH', None, 'PL7 4QN'),
 ('Private Limited Company', 'TORQUAY', 'DEVON', 'TQ1 4PR'),
 ('Private Limited Company', 'ROSSENDALE', 'LANCASHIRE', 'BB4 8HH'),
 ('Private Limited Company', 'GATESHEAD', 'TYNE AND WEAR', 'NE11 9SY'),
 ('Private Limited Company', 'CARDIFF', '-', 'CF10 4SP'),
 ('Private Limited Company', 'BIRMINGHAM', 'WEST MIDLANDS', 'B3 1HL'),
 ('Private Limited Company', 'APSLEY WAY', None, 'NW2 7HF'),
 ('Private Limited Company', 'LONDON', None, 'WC2A 2JR'),
 ('Private Limited Company', 'SUTTON COLDFIELD', 'WEST MIDLANDS', 'B75 5BE'),
 ('Private Limited Company', 'LONDON', None, 'N14 6JS'),
 ('Private Limited Company', 'LONDON', None, 'W1F 9QW'),
 ('Private Limited Company', 'LONDON', 'LONDON', 'N15 4QL'),
 ('Private Limited Company', 'BROMLEY', 'KENT', 'BR1 2RU'),
 ('Private Limited Company', 'GRIMSBY', None, 'DN31 2LP'),
 ('Private Limited Company', 'MILTON KEYNES', None, 'MK11 1AQ'),
 ('Private Limited Company', 'PONTEFRACT', None, 'WF8 2FF'),
 ('Private Limited Company', 'WATFORD', None, 'WD18 7RR'),
 ('Private Limited Company', 'GRANTHAM', None, 'NG32 3PD'),
 ('Private Limited Company', 'NEWPORT', None, 'NP19 0AS'),
 ('Private Limited Company', 'WINCHESTER', 'HAMPSHIRE', 'SO21 2JH'),
 ('Private Limited Company', 'LONDON', None, 'WC2A 2JR'),
 ('PRI/LTD BY GUAR/NSC (Private, limited by guarantee, no share capital)',
  'HARLOW',
  'ESSEX',
  'CM20 1QP'),
 ('Private Limited Company', 'ROTHERHAM', 'SOUTH YORKSHIRE', 'S60 1DX'),
 ('Private Limited Company', 'STOCKPORT', 'ENGLAND', 'SK2 7LZ'),
 (None, None, None, None),
 ('Private Limited Company', 'LONDON', None, 'E2 6FX'),
 ('Private Limited Company', 'LONDON', None, 'WC2A 1ET'),

In [65]:
add_on = pd.DataFrame(result, columns=["company_type", "town", "county", "post_code"])
add_on

,company_type,town,county,post_code
0,Private Limited Company,POTTERS BAR,HERTFORDSHIRE,EN6 2DA
1,Private Limited Company,LONDON,GREATER LONDON,WC2H 9JQ
2,Private Limited Company,EDENBRIDGE,NaN,TN8 5NF
3,Private Limited Company,ABERDEEN,NaN,AB11 7SY
4,Private Limited Company,GREAT WAKERING,ESSEX,SS3 0GW
...,...,...,...,...
13539,"PRI/LTD BY GUAR/NSC (Private, limited by guara...",BERKHAMSTED,NaN,HP4 2EG
13540,Private Limited Company,LONDON,NaN,E6 3RX
13541,Private Limited Company,LEICESTER,NaN,LE7 7NF
13542,Private Limited Company,LIVERPOOL,NaN,L23 5RE
13543,Private Limited Company,CRANLEIGH,SURREY,GU6 7FL

In [67]:
pd.concat([raw_val, add_on], axis=1).to_csv(f'{Path.cwd() / "6_7_2026_out.csv"}', index=False)

In [68]:
results

[('Private Limited Company', 'CRANLEIGH', 'SURREY', 'GU6 7FL')]

In [69]:
data = pd.DataFrame(results, columns=["com_num","name", "sic_code"])

ValueError: 3 columns passed, passed data had 4 columns

In [70]:
final = data.iloc[30000:40000]
index = "[30000-40000]"

In [18]:
final

        com_num                                               name sic_code
30000  11267284                           20 NS MANAGEMENT LIMITED    68209
30001  05686727  20 OAKSFORD AVENUE ENFRANCHISEMENT COMPANY LIM...    55900
30002  07217524                               20 OBAN ROAD LIMITED    68100
30003  SC846178                                          20 OF LTD    73110
30004  SC846178                                          20 OF LTD    82990
...         ...                                                ...      ...
39995  16352322                    2717 PRESERVATION GROUP LIMITED    33170
39996  16352322                    2717 PRESERVATION GROUP LIMITED    49390
39997  16352322                    2717 PRESERVATION GROUP LIMITED    91020
39998  16352322                    2717 PRESERVATION GROUP LIMITED    94990
39999  11890449                                      271HR LIMITED    70229

[10000 rows x 3 columns]

In [19]:
final.to_csv(Path.cwd().parent / f"com_names_n_codes{index}.csv", index=False)

In [49]:
data[data["CompanyName"] == '"243 RUGBY ROAD MANAGEMENT COMPANY LIMITED"']

,CompanyName,CompanyNumber,RegAddress.CareOf,RegAddress.POBox,RegAddress.AddressLine1,RegAddress.AddressLine2,RegAddress.PostTown,RegAddress.County,RegAddress.Country,RegAddress.PostCode,...,PreviousName_7.CONDATE,PreviousName_7.CompanyName,PreviousName_8.CONDATE,PreviousName_8.CompanyName,PreviousName_9.CONDATE,PreviousName_9.CompanyName,PreviousName_10.CONDATE,PreviousName_10.CompanyName,ConfStmtNextDueDate,ConfStmtLastMadeUpDate
13,"""243 RUGBY ROAD MANAGEMENT COMPANY LIMITED""",05914136,NaN,NaN,STONEMEAD HOUSE,95 LONDON ROAD,CROYDON,SURREY,ENGLAND,CR0 2RF,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06/09/2026,23/08/2025