In [55]:
import os
from dotenv import load_dotenv, dotenv_values
from pathlib import Path
import requests
import pandas as pd

load_dotenv(Path("/Users/tanaphan/Documents/STUDY/UoBristol/Final_Project/team_21_lloyds/.env"))

True

In [8]:
API_KEY = os.getenv("API_KEY_GUARDIAN")

In [125]:
from bs4 import BeautifulSoup

def html_remover(raw):
    if not raw:
        return ""
    soup = BeautifulSoup(raw, "html.parser")
    html_cleaned = soup.get_text()
    return html_cleaned

In [ ]:
def pull_news(KEYWORD):
    response = requests.get(
    "https://content.guardianapis.com/search",
    params={
        "q": KEYWORD,
        "api-key": API_KEY,
        "page-size": 50,
        "order-by": "newest",
        # "section": "business",
        "show-fields": "trailText,headline,body,wordcount,lastModified",
        "show-tags": "keyword"
    })
    
    data = response.json()["response"]
    articles = data.get("results", [])

    print(f"Status: {data['status']}")
    print(f"Total Articles: {data['total']}")
    print(f"Total Pages: {data['pages']}")

    rows = []
    for article in articles:
        fields = article.get("fields", {})
        tags = article.get("tags", [])
        tag_names = []
        for tag in tags:
            tag_names.append(tag["webTitle"])

        rows.append({
            "title": article.get("webTitle", ""),
            "section": article.get("sectionName", ""),
            "date": article.get("webPublicationDate", ""),
            "url": article.get("webUrl", ""),
            "trail_text": fields.get("trailText", ""),
            "wordcount": fields.get("wordcount", None),
            "tags": tag_names,
            "body": html_remover(fields.get("body", ""))
        })

    df = pd.DataFrame(rows)
    return df

In [161]:
df = pull_news('"Lloyds Bank" AND SME')

Status: ok
Total Articles: 17
Total Pages: 1

In [162]:
df.head()

,title,section,date,url,trail_text,wordcount,tags,body
0,Public sector pay rises unlikely to drive up i...,Business,2024-08-01T16:15:43Z,https://www.theguardian.com/business/live/2024...,City economists predict further cut in Novembe...,8542,"[Business, Economics, Stock markets, FTSE, Ban...",5.08pm BST Shares in low-cost airline Wizz...
1,UK and US manufacturing sectors shrink as new ...,Business,2024-05-01T15:44:48Z,https://www.theguardian.com/business/live/2024...,The UK’s manufacturing sector suffered a fresh...,4746,"[Business, Economics, Stock markets, FTSE]",4.44pm BST Closing post That’s all for tod...
2,UK recession fears swirl as factory output fal...,Business,2023-08-01T15:57:10Z,https://www.theguardian.com/business/live/2023...,Nationwide reports average house prices fell 3...,7359,"[Business, Economics, Stock markets, House pri...",4.57pm BST Closing post Time to recap… The...
3,Jobs at risk as Morrisons shuts 132 McColl’s s...,Business,2022-11-01T15:54:58Z,https://www.theguardian.com/business/live/2022...,Supermarket chain plans to close loss-making M...,6287,"[Business, Economics, Stock markets, BP, House...",3.53pm GMT Closing summary Time to recap. ...
4,UK house price slowdown ‘on way’; factory grow...,Business,2022-06-01T14:56:43Z,https://www.theguardian.com/business/live/2022...,Rolling coverage of the latest economic and fi...,4780,"[Business, Economics, Stock markets, Housing m...",3.56pm BST Closing summary Time to recap T...

In [ ]:
# df.to_csv(f"TheGuardian.csv", index=False)

--------------------------------------------------

In [ ]:
# response = requests.get(
#     "https://content.guardianapis.com/search",
#     params={
#         "q": f'"{KEYWORD}"',
#         "api-key": API_KEY,
#         "page-size": 50,
#         "order-by": "newest",
#         "section": "business",
#         "show-fields": "trailText,headline,body,wordcount,lastModified",
#         "show-tags": "keyword"
#     },
#     timeout=10,
# )

# data = response.json()["response"]
# articles = data.get("results", [])

# print(f"Status: {data['status']}")
# print(f"Total Articles: {data['total']}")
# print(f"Total Pages: {data['pages']}")

Status: ok
Total Articles: 0
Total Pages: 0

In [ ]:
# articles

[{'id': 'business/2026/jul/19/bank-of-england-bonds-coal-loans-assets',
  'type': 'article',
  'sectionId': 'business',
  'sectionName': 'Business',
  'webPublicationDate': '2026-07-19T05:00:17Z',
  'webTitle': 'Bank of England to stop accepting bonds linked to coal for key loans',
  'webUrl': 'https://www.theguardian.com/business/2026/jul/19/bank-of-england-bonds-coal-loans-assets',
  'apiUrl': 'https://content.guardianapis.com/business/2026/jul/19/bank-of-england-bonds-coal-loans-assets',
  'fields': {'headline': 'Bank of England to stop accepting bonds linked to coal for key loans',
   'trailText': 'Campaigners hope move will will force commercial banks to rethink holding assets linked to the fossil fuel',
   'body': '<p>Climate campaigners have declared a victory after the Bank of England said it would no longer accept bonds linked to one of the most polluting industries on the planet for key loan arrangements.</p> <p>The ban, which comes into force in October, marks a fresh crackdown on thermal coal, which is burned in power plants to create electricity, and has <a href="https://www.theguardian.com/business/2025/sep/25/bank-of-england-tackle-climate-crisis-mark-carney-greepeace">long been a target of green policy activists</a>.</p> <p>The Bank’s new policy suggests that bonds linked to thermal coal are now too risky to sit on its balance sheet, as an international shift away from dirty fossil fuels towards greener energy could end up wiping out their value.</p> <p>“It’s a strong signal from a central bank, and to the market as well,” Ellie McLaughlin, a senior policy and advocacy manager at the campaign group Positive Money, told the Guardian.</p> <p>Earlier this summer the Bank of England quietly announced it would no longer let commercial banks use bonds linked to the thermal coal as “collateral” when they borrowed money from the central bank.</p> <p>The central bank regularly issues loans to commercial banks such as Barclays, Lloyds, NatWest and HSBC to ensure they can settle transactions and keep operations running smoothly. Those commercial banks have to provide collateral, usually in the form of bonds, as a guarantee, meaning they would be kept by the central bank if they failed to repay their loans.</p> <p>About 150 of the world’s largest financial companies already have some sort of restrictions on how they do business with the thermal coal industry, according to figures published by the Paris-based non-profit Reclaim Finance last September.</p> <p>However, activists are hoping the new policy will force commercial banks to rethink holding assets linked to thermal coal – which is one of the most polluting fossil fuels on the planet – on their balance sheets.</p> <p>The Bank of England explained in <a href="https://www.bankofengland.co.uk/markets/market-notices/2026/june/collateral-eligibility-in-the-smf-11-june-2026">its policy statement</a> that thermal coal companies “can be exposed to potential financial risks connected to the adjustment of the economy towards net zero”. It added that the Bank would also discount the value of bonds in other relevant sectors “to protect the Bank against financial risks”.</p> <p>The policy is far more strict than those currently adopted by most of its western counterparts, including the European Central Bank. However, the Bank of England made little fanfare of its announcement, having quietly released the policy on its website in early June.</p> <p>“The Bank of England has been much less vocal about this and its wider climate work in recent years, for kind of various reasons,” McLaughlin said.</p> <p>It comes amid a US-led backlash against green policies that have forced most financial companies to row back on their climate goals since Donald Trump returned to the White House. “It does make that environment within which they operating much more difficult,” McLaughlin added.</p> <p>However, how effective the Bank of England’s policy is will depend on its design.</p> <p>“We’ve yet to see how the Bank will calculate haircuts to account for climate risks, and exclusions should extend beyond thermal coal to cover all ‘always harmful’ activities,” McLaughlin said, including any fossil fuel expansion or deforestation.</p> <p>“It’s quite significant, but there are definitely a lot of areas where the Bank could be going further.”</p>',
   'wordcount': '536',
   'lastModified': '2026-07-19T18:52:10Z'},
  'tags': [{'id': 'business/bankofenglandgovernor',
    'type': 'keyword',
    'sectionId': 'business',
    'sectionName': 'Business',
    'webTitle': 'Bank of England',
    'webUrl': 'https://www.theguardian.com/business/bankofenglandgovernor',
    'apiUrl': 'https://content.guardianapis.com/business/bankofenglandgovernor',
    'references': [],
    'keywordType': 'organisation'},
   {'id': 'business/energy-industry',
    'type': 'keyword',
    'sectionId': 'business',
    'sectionName': 'Business',
    'webTitle': 'Energy industry',
    'webUrl': 'https://www.theguardian.com/business/energy-industry',
    'apiUrl': 'https://content.guardianapis.com/business/energy-industry',
    'references': [],
    'keywordType': 'other'},
   {'id': 'business/banking',
    'type': 'keyword',
    'sectionId': 'business',
    'sectionName': 'Business',
    'webTitle': 'Banking',
    'webUrl': 'https://www.theguardian.com/business/banking',
    'apiUrl': 'https://content.guardianapis.com/business/banking',
    'references': [],
    'keywordType': 'other'},
   {'id': 'business/business',
    'type': 'keyword',
    'sectionId': 'business',
    'sectionName': 'Business',
    'webTitle': 'Business',
    'webUrl': 'https://www.theguardian.com/business/business',
    'apiUrl': 'https://content.guardianapis.com/business/business',
    'references': [],
    'keywordType': 'other'},
   {'id': 'environment/coal',
    'type': 'keyword',
    'sectionId': 'environment',
    'sectionName': 'Environment',
    'webTitle': 'Coal',
    'webUrl': 'https://www.theguardian.com/environment/coal',
    'apiUrl': 'https://content.guardianapis.com/environment/coal',
    'references': [],
    'keywordType': 'other'},
   {'id': 'environment/energy',
    'type': 'keyword',
    'sectionId': 'environment',
    'sectionName': 'Environment',
    'webTitle': 'Energy',
    'webUrl': 'https://www.theguardian.com/environment/energy',
    'apiUrl': 'https://content.guardianapis.com/environment/energy',
    'references': [],
    'keywordType': 'other'},
   {'id': 'environment/environment',
    'type': 'keyword',
    'sectionId': 'environment',
    'sectionName': 'Environment',
    'webTitle': 'Environment',
    'webUrl': 'https://www.theguardian.com/environment/environment',
    'apiUrl': 'https://content.guardianapis.com/environment/environment',
    'references': [],
    'keywordType': 'other'},
   {'id': 'uk/uk',
    'type': 'keyword',
    'sectionId': 'uk-news',
    'sectionName': 'UK news',
    'webTitle': 'UK news',
    'webUrl': 'https://www.theguardian.com/uk/uk',
    'apiUrl': 'https://content.guardianapis.com/uk/uk',
    'references': [],
    'keywordType': 'other'},
   {'id': 'environment/fossil-fuels',
    'type': 'keyword',
    'sectionId': 'environment',
    'sectionName': 'Environment',
    'webTitle': 'Fossil fuels',
    'webUrl': 'https://www.theguardian.com/environment/fossil-fuels',
    'apiUrl': 'https://content.guardianapis.com/environment/fossil-fuels',
    'references': [],
    'keywordType': 'other'}],
  'isHosted': False,
  'pillarId': 'pillar/news',
  'pillarName': 'News'},
 {'id': 'business/nils-pratley-on-finance/2026/jul/15/victory-nationwide-board-members-deserve-stronger-voting-rights',
  'type': 'article',
  'sectionId': 'business',
  'sectionName': 'Business',
  'webPublicationDate': '2026-07-15T17:18:48Z',
  'webTitle': ' A victory for Nationwide’s board – but members still deserve stronger voting rights | Nils Pratley',
  'webUrl': 'https://www.theguardian.com/business/nils-pratley-on-finance/2026/jul/15/victory-nationwide-board-members-deserve-stronger-voting-rights',
  'apiUrl': 'https://content.guardianapis.com/business/nils-pratley-on-finance/2026/jul/15/victory-nationwide-board-members-deserve-stronger-voting-rights',
  'fields': {'headline': ' A victory for Nationwide’s board – but members still deserve stronger voting rights',
   'trailText': 'Building society rules need an overhaul if ballots on executive pay are non-binding and huge takeovers don’t require approval',
   'body': '<p>In the end, the rebellion at Nationwide, the country’s biggest building society, was modest. James Sherwin-Smith, who was trying to become the first member-nominated director in almost 25 years, <a href="https://www.theguardian.com/business/2026/jul/15/nationwide-customer-board-building-society">secured only 12% of votes cast</a> – enough to count as unusual but a long way short of causing embarrassment for the board. Meanwhile, the society got its usual 95%-plus majorities on every other resolution, including the advisory one on directors’ pay.</p> <p>There are two ways the directors could react to this result. The first is to conclude that everything is tickety-boo at the UK’s most important mutual. The society’s financial performance is undeniably strong, after all, and the scores for customer satisfaction remain streets ahead of those of the shareholder-owned banks. In operational terms, a lot is going right at Nationwide. That helps to explain why the members are not clamouring to register dissatisfaction, or, indeed, to register much at all: only about 600,000 out of 19 million voted at the annual meeting.</p> <p>The more far-sighted approach, however, would be to concede that one cannot rely on the skies remaining permanently sunny. In a different operating climate, some of Sherwin-Smith’s points about the meaning of accountability at a member-owned organisation might prove harder for the bosses to bat away.</p> <p>It remains bizarre that Nationwide’s members did not get to vote on <a href="https://www.theguardian.com/business/2024/mar/21/nationwide-agrees-29bn-deal-to-take-over-virgin-money">the £2.9bn takeover of Virgin Money in 2024</a>, a deal that took the society into a bigger league by expanding the balance sheet by a third. The formal reason made only legalistic sense: the 1986 Building Societies Act did not require a vote and the takeover code, with an eye on protecting the interests of target companies, doesn’t encourage voluntary conditions to be attached to an offer. But the logical conclusion to be drawn from that episode was that the building society rules need an overhaul. If Nationwide, through success, is now in the business of multibillion takeovers, the owners surely need a real say in future adventures.</p> <p>Equally, it is unsatisfactory that Nationwide continues to plead “them’s the building society rules” as an explanation for why its votes on pay are non-binding. On that front, it could just show leadership and fall into line with the shareholder-owned banks whose greedy ways Nationwide likes to attack in its adverts. When its <a href="https://www.theguardian.com/business/2026/jun/08/nationwide-ceo-pay-package-bonus-debbie-crosbie-virgin-money">chief executive, Debbie Crosbie, is getting £4.7m</a> – not Lloyds or NatWest levels but definitely not small change either – you’d think Nationwide itself would see the merit in getting more than a confirmatory thumbs up from the ranks. In another year, pay is an issue that could blow up.</p> <p>One of Sherwin-Smith’s particular beefs was about the “quick vote” system that allows a Nationwide member to click one box and back the board on all resolutions. Did it load the dice against the rebel candidate? Well, not to a degree that would have altered the outcome. But, again, it’s a feature that sends a “trust us” message from the boardroom that is at odds with the member-owned ethos.</p> <p>None of which is to suggest that Nationwide needs a radical overhaul. To repeat, it’s a high-performing operation. And, in a more tightly regulated financial services world, it is probably simply harder for member-nominated directors to become common at building societies again. But Nationwide has an incoming chair, Mike Rogers, a former chair of the insurer Admiral and the credit-checking group Experian, who has a chance to look afresh at governance at a time of heightened political interest in <a href="https://www.theguardian.com/business/2026/may/24/nationwide-governance-agm-building-societies-boards">how mutuals are run</a>. At a minimum, membership ought to mean real votes on takeovers and boardroom pay.</p>',
   'wordcount': '596',
   'lastModified': '2026-07-15T18:11:35Z'},
  'tags': [{'id': 'business/business',
    'type': 'keyword',
    'sectionId': 'business',
    'sectionName': 'Business',
    'webTitle': 'Business',
    'webUrl': 'https://www.theguardian.com/business/business',
    'apiUrl': 'https://content.guardianapis.com/business/business',
    'references': [],
    'keywordType': 'other'},
   {'id': 'business/nationwide',
    'type': 'keyword',
    'sectionId': 'business',
    'sectionName': 'Business',
    'webTitle': 'Nationwide',
    'webUrl': 'https://www.theguardian.com/business/nationwide',
    'apiUrl': 'https://content.guardianapis.com/business/nationwide',
    'references': [],
    'keywordType': 'organisation'},
   {'id': 'money/banks',
    'type': 'keyword',
    'sectionId': 'money',
    'sectionName': 'Money',
    'webTitle': 'Banks and building societies',
    'webUrl': 'https://www.theguardian.com/money/banks',
    'apiUrl': 'https://content.guardianapis.com/money/banks',
    'references': [],
    'keywordType': 'other'},
   {'id': 'money/money',
    'type': 'keyword',
    'sectionId': 'money',
    'sectionName': 'Money',
    'webTitle': 'Money',
    'webUrl': 'https://www.theguardian.com/money/money',
    'apiUrl': 'https://content.guardianapis.com/money/money',
    'references': [],
    'keywordType': 'other'},
   {'id': 'uk/uk',
    'type': 'keyword',
    'sectionId': 'uk-news',
    'sectionName': 'UK news',
    'webTitle': 'UK news',
    'webUrl': 'https://www.theguardian.com/uk/uk',
    'apiUrl': 'https://content.guardianapis.com/uk/uk',
    'references': [],
    'keywordType': 'other'},
   {'id': 'business/executive-pay-bonuses',
    'type': 'keyword',
    'sectionId': 'business',
    'sectionName': 'Business',
    'webTitle': 'Executive pay and bonuses',
    'webUrl': 'https://www.theguardian.com/business/executive-pay-bonuses',
    'apiUrl': 'https://content.guardianapis.com/business/executive-pay-bonuses',
    'references': [],
    'keywordType': 'other'},
   {'id': 'business/corporate-governance',
    'type': 'keyword',
    'sectionId': 'business',
    'sectionName': 'Business',
    'webTitle': 'Corporate governance',
    'webUrl': 'https://www.theguardian.com/business/corporate-governance',
    'apiUrl': 'https://content.guardianapis.com/business/corporate-governance',
    'references': [],
    'keywordType': 'other'}],
  'isHosted': False,
  'pillarId': 'pillar/news',
  'pillarName': 'News'},
 {'id': 'business/2026/jul/10/bank-of-england-handed-powers-to-regulate-key-tech-firms-including-amazon-and-google',
  'type': 'article',
  'sectionId': 'business',
  'sectionName': 'Business',
  'webPublicationDate': '2026-07-10T14:37:13Z',
  'webTitle': 'Bank of England handed powers to regulate key tech firms including Amazon and Google',
  'webUrl': 'https://www.theguardian.com/business/2026/jul/10/bank-of-england-handed-powers-to-regulate-key-tech-firms-including-amazon-and-google',
  'apiUrl': 'https://content.guardianapis.com/business/2026/jul/10/bank-of-england-handed-powers-to-regulate-key-tech-firms-including-amazon-and-google',
  'fields': {'headline': 'Bank of England handed powers to regulate key tech firms including Amazon and Google',
   'trailText': 'Direct oversight of ‘critical third parties’ such as Oracle and Microsoft given to ensure resilient cyber-defences and help safeguard UK economy',

In [ ]:
# rows = []
# for article in articles:
#     fields = article.get("fields", {})
#     tags = article.get("tags", [])
#     tag_names = []
#     for tag in tags:
#         tag_names.append(tag["webTitle"])

#     rows.append({
#         "title": article.get("webTitle", ""),
#         "date": article.get("webPublicationDate", ""),
#         "url": article.get("webUrl", ""),
#         "trail_text": fields.get("trailText", ""),
#         "wordcount": fields.get("wordcount", None),
#         "tags": tag_names,
#         "body": html_remover(fields.get("body", ""))
#     })

# df = pd.DataFrame(rows)

In [ ]:
# df.head()

,title,date,url,trail_text,wordcount,tags,body
0,Bank of England to stop accepting bonds linked...,2026-07-19T05:00:17Z,https://www.theguardian.com/business/2026/jul/...,Campaigners hope move will will force commerci...,536,"[Bank of England, Energy industry, Banking, Bu...",Climate campaigners have declared a victory af...
1,A victory for Nationwide’s board – but member...,2026-07-15T17:18:48Z,https://www.theguardian.com/business/nils-prat...,Building society rules need an overhaul if bal...,596,"[Business, Nationwide, Banks and building soci...","In the end, the rebellion at Nationwide, the c..."
2,Bank of England handed powers to regulate key ...,2026-07-10T14:37:13Z,https://www.theguardian.com/business/2026/jul/...,Direct oversight of ‘critical third parties’ s...,566,"[Bank of England, Financial Conduct Authority,...",The Bank of England has been handed powers to ...
3,Apollo gatecrashes easyJet sale with surprise ...,2026-07-10T14:07:51Z,https://www.theguardian.com/business/live/2026...,Rolling coverage of the latest economic and fi...,3307,"[Business, Stock markets, FTSE]",3.07pm BST Closing post Time to wrap up… T...
4,Reeves to launch City ‘skills compact’ committ...,2026-07-10T05:00:12Z,https://www.theguardian.com/business/2026/jul/...,Exclusive: Plan to improve skills of thousands...,666,"[Financial sector, AI (artificial intelligence...",Chancellor Rachel Reeves is to announce a new ...